### ISSUE TITLE
async API

### ISSUE THREAD

**Issue by Naxdy** [rscarson/rustyscript#142]
I've noticed that under the hood, rustyscript is using tokio runtimes in order to execute the js code. Seeing as under the hood, a lot of async stuff is happening already, it would be pretty awesome if there was an async api exposed that we could use, for example:

```rust
let result = runtime.call_entrypoint_async::<Value>(&module_handle, json_args!()).await?;
```

Thanks for considering :)

**Comment by rscarson** [comment]
I'm actually working on that! 0.5 should hopefully come out today, and async should be available in the next release after that

**Comment by rscarson** [comment]
0.5.0 is now feature complete 
Publication is pending an issue with GitHub ci disk space

**Comment by spolu** [comment]
@rscarson is the new _async code resilient to this: https://github.com/denoland/deno_core/issues/150 in your opinion?

I didn't directly try yet but inspecting the code I expect the JsRuntime deletion to be problematic when run from a multi-threaded environment such as an Axum server?

**Comment by rscarson** [comment]
This shouldn't affect you as long as the runtimes are run on seperate threads

This issue is only for many-runtime-one-thread implementations

Which I concur with mmastrac is not recommended anyway

**Comment by spolu** [comment]
I will give a spin to rustyrust in our axum / tokio mutli_thread environment but I've tried everything (thread::spawn, tokio::task::spawn_blocking + building a new runtime + block_on) and they all lead to a seg fault :/

It might be because it does not comply to the requirement expressed here: https://docs.rs/deno_core/latest/deno_core/struct.JsRuntime.html#method.main_context

> Note: since V8 11.6, all runtimes must have a common parent thread that initalized the V8 platform. This can be done by calling [JsRuntime::init_platform](https://docs.rs/deno_core/latest/deno_core/struct.JsRuntime.html#method.init_platform) explicitly, or it will be done automatically on the calling thread when the first runtime is created.

**Comment by rscarson** [comment]
> I will give a spin to rustyrust in our axum / tokio mutli_thread environment but I've tried everything (thread::spawn, tokio::task::spawn_blocking + building a new runtime + block_on) and they all lead to a seg fault :/
> 
> It might be because it does not comply to the requirement expressed here: https://docs.rs/deno_core/latest/deno_core/struct.JsRuntime.html#method.main_context
> 
> > Note: since V8 11.6, all runtimes must have a common parent thread that initalized the V8 platform. This can be done by calling [JsRuntime::init_platform](https://docs.rs/deno_core/latest/deno_core/struct.JsRuntime.html#method.init_platform) explicitly, or it will be done automatically on the calling thread when the first runtime is created.
> 
> I presume the only way to provide proper isolation + real async interface is to use channels between a main thread that spawn individual threads for each jsruntime and the usage point which may be on any thread from the tokio multi-thread runtime.
> 
> wdyt? Would be very nice to provide this setup out of the box :)

Good catch - 0.5.0 will have `utilities::init_platform` as well as the associated documentation fixes!

**Comment by spolu** [comment]
ooc What's your recommended way to ensure each jsruntime is on its own thread in a tokio context?

**Comment by rscarson** [comment]
> ooc What's your recommended way to ensure each jsruntime is on its own thread in a tokio context?

Each `Worker` runs in a thread on their own Tokio runtime

It should be possible to give the worker's runtime a context and have a worker controller initialize the platform and manage a pool of them

**Comment by rscarson** [comment]
> ooc What's your recommended way to ensure each jsruntime is on its own thread in a tokio context?

The worker always runs on a seperate thread

You might just need a custom worker managed by a controller that initializes runtime and manages the pool

**Comment by spolu** [comment]
FYI went with this which is what I think you really want when working from another multi threaded tokio runtime in very arbitrary ways: https://github.com/dust-tt/dust/blob/main/core/src/deno/js_executor.rs

**Comment by rscarson** [comment]
Fixed in 0.5.0

**Comment by janderadutra** [comment]
Using the axum async server, the only way I was able to execute a function was with DefaultWorker, is there another way? Thanks

**Comment by rscarson** [comment]
> Using the axum async server, the only way I was able to execute a function was with DefaultWorker, is there another way? Thanks 

Can you open a new issue for this with more details and specifics?
