### ISSUE TITLE
Make `export default fn` the default module entry point

### ISSUE THREAD

**Issue by RunDevelopment** [rscarson/rustyscript#158]
**Is your feature request related to a problem? Please describe.**
The first example code block in the README uses `rustyscript.register_entrypoint` to register to entry point for the module. However, there's already the ESM `export default <expr>` syntax, which has similar semantics, and is likely a more natural fit.

**Describe the solution you'd like**
Support `export default <fn expr>` as an alternate way to register entry points.

**Additional context**
I first suggested this [on reddit](https://www.reddit.com/r/rust/comments/1e0tq5n/comment/lctm6aw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

**Comment by rscarson** [comment]
Available in `0.5.2`
If `register_entrypoint` gets called, it will take priority over the default export
That way, a module has the option of having a default export that is not the entrypoint if need-be

And if neither are available, the default entrypoint in the runtime's options will be tried, as before
