### ISSUE TITLE
How can I capture `console.{log,error,info,trace}` output in the Rust host?

### ISSUE THREAD

**Issue by Boscop** [rscarson/rustyscript#222]
How can I capture `console.{log,error,info,trace}` output in the Rust host? 🙂
So that it doesn't get automatically printed to stdout, but the host can display it where it wants, e.g. in its frontend UI.

**Comment by rscarson** [comment]
The easiest way is to create a wrapper function around the console log functions

Eg;
```js
let log = console.log;
console.log = function(s) {
  [ Rust calls ]
  log(s)
}
```

**Comment by Boscop** [comment]
Thanks 🙏
