### ISSUE TITLE
Crashing on winit app close

### ISSUE THREAD

**Issue by BrianWiz** [rscarson/rustyscript#224]
**Describe the bug**
I'm not sure if it's a bug or something I'm missing but I get the following crash when I close my `winit` application via the window close button.

```
thread 'main' panicked at C:\Users\Brian\.cargo\registry\src\index.crates.io-6f17d22bba15001f\v8-0.99.0\src\isolate.rs:1616:7:
v8::OwnedIsolate instances must be dropped in the reverse order of creation. They are entered upon creation and exited upon being dropped.
```

**To Reproduce**
I haven't made a minimal example yet, working on one now. But essentially what I have is a runtime per game object, created at the start of the app. I then hit close on the window, and get this crash. Interestingly enough, when running in debug mode in RustRover, when I hit the stop button it doesn't crash.

**Desktop:**
 - OS: Windows

**Additional context**
Building a custom game engine, loving rustyscript!!!

**Comment by utyfua** [comment]
I believe Its part of deno rusty v8 and cannot be fixed on level of this library.

I did bypass it creating each runtime on a separate process so it can be safely destroyed.

Probably it will be enough if you manually destroy your runtimes manually in the rigth order to avoid errors if you dont want to create child processes.

UPD: using process threads now instead

**Comment by rscarson** [comment]
The worker module may be useful to you
It lets the runtime survive in a seperate thread to prevent the need to destroy them

Alternatively, as was already said,
Whenever you destroy created runtimes, you must be sure to drop them newest-to-oldest

**Comment by BrianWiz** [comment]
Thanks guys, it'll take a bit for me to refactor so I can actually do that reliably but I'd say this is solved for now.
