### ISSUE TITLE
Enable full Deno-like module resolution for npm and node

### ISSUE THREAD

**Issue by ahmedxfn** [rscarson/rustyscript#237]
**Is your feature request related to a problem? Please describe.**

I’m using `rustyscript` to build a plugin system in my Rust application, where users can write their own plugins in JavaScript/TypeScript. However, I face issues when importing modules using the `npm:` or `node:` schemes, such as:

```typescript
import chalk from "npm:chalk@5";
import os from "node:os";
```

These imports result in errors like `"unrecognized schema for module import"`, as `rustyscript` doesn’t automatically resolve these module types like the Deno runtime does.

**Describe the solution you'd like**

I’d like `rustyscript` to have built-in support for resolving `npm:` and `node:` modules automatically, achieving a runtime experience similar to the Deno CLI. This would simplify the user experience by avoiding the need to implement custom module loaders.

**Describe alternatives you've considered**

- **Custom Module Loader:** Writing a custom loader to handle these imports, which is complex and requires replicating Deno’s functionality.
- **Using CDNs:** Importing packages from CDNs like `esm.sh`, which doesn’t fully resolve Node.js built-in modules.
- **Bundling with Esbuild:** Bundling all dependencies manually, but this doesn’t solve the problem with `node:` imports.

**Additional context**

The goal is to provide a seamless plugin system where JavaScript/TypeScript plugins can easily import npm packages and Node.js built-ins. Is a custom module loader necessary, or is there an easier way to achieve this in `rustyscript`?

**Comment by rscarson** [comment]
That would be the deno_node extension

It's a massive project that is in progress

**Comment by rscarson** [comment]
I have gotten node working on my private test branch! Expect a version with the feature to hit master this week

**Comment by rscarson** [comment]
`node_experimental` can now be used on the master-branch version

It will be available as of 0.10.0 on the crates.io version

**Comment by ahmedxfn** [comment]
Thank you so much for your efforts in implementing `node_experimental`, I really appreciate your hard work and commitment to improving the project. Is there any donation link or way I can support your work?

**Comment by rscarson** [comment]
> Thank you so much for your efforts in implementing `node_experimental`, I really appreciate your hard work and commitment to improving the project. Is there any donation link or way I can support your work?

Thank you so much! I do accept contributions to the project [here](https://buymeacoffee.com/rscarson)
