### ISSUE TITLE
Failed to resolve: could not find `deno_tls` in `rustyscript`

### ISSUE THREAD

**Issue by utyfua** [rscarson/rustyscript#291]
Before I could use `rustyscript::deno_tls::Proxy` but in 0.11.0 i cannot anymore
```
Failed to resolve: could not find `deno_tls` in `rustyscript`
```

Is it intentional?

**Comment by rscarson** [comment]
The `deno_tls` export has been moved into `rustyscript::extensions::deno_tls` to match the  rest of the extension exports

**Comment by utyfua** [comment]
Thanks!
