### ISSUE TITLE
Cache an imported module 

### ISSUE THREAD

**Issue by gc-victor** [rscarson/rustyscript#81]
Is there any way to cache an imported module? I'm importing the `https://deno.land/std@0.217.0/encoding/base64.ts.` and it's slow. I want to use it consistently. What is your recommendation to do it?

Reference:
https://github.com/rscarson/rustyscript/blob/0fd168e3b82106c3c4551f1e744b113e26f2b109/examples/url_import.rs#L28C1-L29C1

**Comment by rscarson** [comment]
The Runtime instance should cache it for its lifetime - is it slow to initially load?
You could always download it and it's dependencies

[Seems its only this and one other file](https://github.com/denoland/deno_std/blob/main/encoding/base64.ts)

If it is slow in other places than on load there may be a deeper issue

**Comment by gc-victor** [comment]
It is slow during the initial load, but as the lifetime is short, it is a problem for my use case.

Thanks for the link. I found it, too, and I was thinking of copying and pasting it to an extension. It is probably the best option.
