### ISSUE TITLE
Could not reset the runtime

### ISSUE THREAD

**Issue by gc-victor** [rscarson/rustyscript#82]
I'm having this error when executing the `soft_reset` function.

`Could not reset the runtime: Runtime("ext:rustyscript/rustyscript.js:53: Uncaught TypeError: Cannot read properties of undefined (reading 'global_backup')")`

**Comment by rscarson** [comment]
Unfortunately the soft_reset and reset functions are currency not working due to changes in deno

What's your usecase for it?

**Comment by gc-victor** [comment]
I have created a work around for it. Thanks!
