### ISSUE TITLE
how to auto cache url import to disk

### ISSUE THREAD

**Issue by i18n-now** [rscarson/rustyscript#86]
as title

**Comment by rscarson** [comment]
I've added a `ModuleCacheProvider` trait you will be able to implement in the next version to provide caching

**Comment by rscarson** [comment]
To give more details on how this will work; `RuntimeOptions` now has a `module_cache` property
Which will be a boxed instance of a type implementing the `module_loader::ModuleCacheProvider` trait

You will find `DefaultModuleCacheProvider` in `module_loader.rs` as an example of how to implement it
You should be able to use that to perform disk caching how you wish

**Comment by rscarson** [comment]
Fixed in version `0.4.0`
