### ISSUE TITLE
I can implement fs.readFileSync to read files. But, what I want is: import {readFileSync} from 'fs' (so the same code is available for nodejs and my runtime)

### ISSUE THREAD

**Issue by i18n-now** [rscarson/rustyscript#87]
I can now implement fs.readFileSync to read files. But, what I want is: import {readFileSync} from 'fs' (so the same code is available for nodejs and my runtime)

How to modify the code to achieve the import effect I want.

https://github.com/i18n-site/ejs/blob/main/src/ext/init_fs/mod.rs
https://github.com/i18n-site/ejs/blob/main/src/ext/init_fs/init_fs.js

```rust
use rustyscript::deno_core::{extension, Extension};

use crate::ext::fs::Permissions;

extension!(
  init_fs,
  deps = [rustyscript],
  esm_entry_point = "ext:init_fs/init_fs.js",
  esm = [ dir "src/ext/init_fs", "init_fs.js" ],
  state = |state| state.put(Permissions{})
);

```

```js
import * as io from "ext:deno_io/12_io.js";
import * as fs from "ext:deno_fs/30_fs.js";

import {
applyToGlobal,
// writeable,
nonEnumerable,
} from "ext:rustyscript/rustyscript.js";

applyToGlobal({
// io: nonEnumerable(io),
fs: nonEnumerable(fs),
// fs: nonEnumerable(fs),
});
```

At the same time, I want to implement 

`import {dirname} form 'path'`

 to actually import the file 

```
deno bundle https://deno.land/std/path/mod.ts path.js
```

I will embed this path.js into the program. Can I do this(In other words, can the search path of the module be customized?
)?

---

deno bundle seems to be deprecated, can use this package path.js

```
deno eval 'import { bundle } from "https://deno.land/x/emit/mod.ts"; const { code } = await bundle(new URL("https://deno.land/std/path/mod.ts")); console.log(code);'| esbuild --minify --bundle --outfile=path.js --format=esm
```

**Comment by rscarson** [comment]
To import code from an extension use `ext:name/path.js` format

For example, if the extension and file you embedded dirname into was called `my_fs/main.js` you'd use `ext:my_fs/main.ks`

**Comment by i18n-now** [comment]
Can you provide an example code under 'example' to demonstrate to impl this requirement? 

I'm not quite clear on how to do it (how to configure 'extension!' )

```
  use rustyscript::deno_core::extension;

  use crate::ext::fs::Permissions;

  /*
     import { readFileSync } from 'fs'
     import { dirname } from 'path'
  */

  extension!(
    init_fs,
    deps = [rustyscript],
    esm_entry_point = "ext:init_fs/init_fs.js",
    esm = [
      dir "src/ext/init_fs", "init_fs.js",
      // dir "src/ext/init_fs", "path.js",
    ],
    state = |state| state.put(Permissions{})
  );
```

**Comment by rscarson** [comment]
Configure what requirement? Sorry I'm not sure I understand

**Comment by i18n-now** [comment]
I mean, if you want to support "
import {readFileSync} from 'fs'
".

How should I write `extension!()` or how should I write `ext:init_fs/init_fs.js`
.

Can you give me a demo code to show how to import a custom built-in module?

**Comment by rscarson** [comment]
Ah I see
Deno requires `./fs`, instead of just `fs`

Your line should read:
```
import {readFileSync} from './fs'
```
