### ISSUE TITLE
ModuleCacheProvider ： set method never called

### ISSUE THREAD

**Issue by i18n-now** [rscarson/rustyscript#88]
<img width="1728" alt="image" src="https://github.com/rscarson/rustyscript/assets/145643935/1e33a313-2bd1-4cb0-a2fd-c9e1257abc39">
as title, I want cache js in `set` , but I found the  `set` method never called

**Comment by rscarson** [comment]
Patch coming later today!

**Comment by rscarson** [comment]
Resolved in 0.4.1
